before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: YinNtlhVniorG0c5FHzqH7HceSpT+AYS75WM2sQdpiVvvrwB9KvKVI/IsT0rCwB8GSZWXZJwbLcrzmjPMthzxiIe4yzXEq2h9POe0FolLy/uNjI5SW2gamebKkUl7BKLa9hzfrpO7fP8UMI2nUAgrffPqCjkE+XNt08PMOhpjrbiKHHZYocLF3LZ/txR2AVjNgof+TQMIyMbUsFta0tcr1hv5anXHtBt34m64qquDnNqXld3L6FS36pIEw0+XeAIkjpbJ/QLmU88abHbs+H2a+VHpvlDDrE4pur+cmeneIx+9t8mGtoW6n65rElSWkbVPU6eOYpA4B2HdX/cMepzKEKAad2t+bGPuNMf+Ypq4RG9Yz5wqkHVgSw7TkXaRdsJVEGePEWAsGk5z5oyHYRlNIQ1nIhO7KK17qaI+AM//p/455aU5U3HarHzalA7v8ZbDGwEtWxxGcLso9tpuXujOb61VGCTDHT5VN4/QRQjmMFp+8W8mmfPvMT03geG53T4nErvqYYYA8JTi2HupYngx88cZtfXM+aCyGD1vN9yXsIBZq3s20tUqb86dJeM3I/JBnF9bp+y20fBmmqqiI4jPzqFkQ4kp0gRVnOCHmWkcyX/91W5MllpHXnni5xHvUBM2FsGhAT6IYDrpGwRf+7/KRXmRn2Uy69YDsjxaDU8Jbw= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
